OUTPUT=/EC:\\TP\\Builds
TPUS=/UQ:\\develop\\Tools\\TP\\tvision

DEBUG=/V /GD

BUILDALLUNITS=/B

INC=/IQ:\\Develop\\Projects\\PASCAL\\INCLUDE

LINK=/L

SWITCHES=#/$$O+ /$$F+ /$$R- /$$X+ /$$B- /$$v- /$$S-



COMPILE=tpc $(TPUS) $(OUTPUT) $(INC) $(DEBUG) $(BUILDALLUNITS) $(LINK)
