OUTPUT=/EQ:\\develop\\Tools\\TP\\tpu
TPUS=/UQ:\\develop\\Tools\\TP\\tvision

DEBUG=/V /GD

BUILDALLUNITS=/B

INCLUDE=/I Q:\\develop\\Tools\\TP\\TVISION

LINK=/L

SWITCHES=#/$$O+ /$$F+ /$$R- /$$X+ /$$B- /$$v- /$$S-

COMPILE=tpc $(TPUS) $(OUTPUT) $(INCLUDE) $(DEBUG) $(BUILDALLUNITS) $(LINK)
