OUTPUT=/EQ:\\develop\\Tools\\TP\\tpu
TPUS=/UQ:\\develop\\Tools\\TP\\tvision

DEBUG=/V /GD

BUILDALLUNITS=/B

INCLUDE=/I Q:\\develop\\Tools\\TP\\TVISION

LINK=/L

#/$O+ /$F+ /$R- /$X+ /$B- /$v-

COMPILE=tpc $(TPUS) $(OUTPUT) $(INCLUDE) $(DEBUG) $(BUILDALLUNITS) $(LINK) 
