include Q:\\develop\\Projects\\PASCAL\\makefile.turbo

all: TVDV.EXE

TVDV.EXE: TVDV.PAS
		$(COMPILE) TVDV.PAS $(SWITCHES)

#		$(COMPILE) TVDVCMDS.PAS $(SWITCHES)
#		$(COMPILE) tvdvdata.pas $(SWITCHES)
#		$(COMPILE) LABHIST.PAS $(SWITCHES)
